Update env_dev.yml

diff --git a/.github/workflows/env_dev.yml b/.github/workflows/env_dev.yml
--- a/.github/workflows/env_dev.yml
+++ b/.github/workflows/env_dev.yml
@@ -73,9 +73,14 @@ jobs:
 
     - name: Run SSH command on target server
       run: |
-         if ! output=$(ssh plm@houenvap7 ".//app/plm/DBA/scripts/deployment_script.sh") echo "$output"
-            echo "Error: Failed to run Script"
+        output=$(ssh plm@houenvap7 ".//app/plm/DBA/scripts/deployment_script.sh")
+        ssh_exit_code=$?
+        if [ $ssh_exit_code -eq 0 ]; then
+            echo "$output"
+        else
+           echo "Error: Failed to run Script"
          fi
+
          
 
           
