Update env_dev.yml

diff --git a/.github/workflows/env_dev.yml b/.github/workflows/env_dev.yml
--- a/.github/workflows/env_dev.yml
+++ b/.github/workflows/env_dev.yml
@@ -73,7 +73,9 @@ jobs:
 
     - name: Run SSH command on target server
       run: |
-         output=$(ssh plm@houenvap7 ".//app/plm/DBA/scripts/deployment_script.sh")
-         echo "$output"
+         if ! output=$(ssh plm@houenvap7 ".//app/plm/DBA/scripts/deployment_script.sh") echo "$output"
+            echo "Error: Failed to run Script"
+         fi
+         
 
           
