Update env_dev.yml

diff --git a/.github/workflows/env_dev.yml b/.github/workflows/env_dev.yml
--- a/.github/workflows/env_dev.yml
+++ b/.github/workflows/env_dev.yml
@@ -26,8 +26,12 @@ jobs:
           # Add commands to create a ZIP archive of your project in the root directory 
           cd PLM_SOURCE/BUILD_MASTER
           zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }}
-          
-    
+      continue-on-error: true
+      # Capture the exit code and display error message if it fails
+      if: ${{ failure() }}
+      run: |
+        echo "Error: Failed to create ZIP archive"
+        exit 1
 
     - name: Create and upload artifact
       uses: actions/upload-artifact@v2
@@ -35,16 +39,44 @@ jobs:
          name: ${{ github.event.inputs.folder_name }}.zip
          path: PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip
 
-    - name: Move the downloaded .zip file to D:/office/DBA
+    - name: Move the downloaded .zip file to Local drive
       run: |     
            mv PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip build/${{ github.event.inputs.folder_name }}.zip
-       
+      continue-on-error: true
+      # Capture the exit code and display error message if it fails
+      if: ${{ failure() }}
+      run: |
+        echo "Error: Failed to move the ZIP file"
+        exit 1
 
     - name: Check out the repository to the runner
       uses: actions/checkout@v4  
+
     - name: Make the script files executable
       run: chmod +x my-script.sh
+      continue-on-error: true
+      # Capture the exit code and display error message if it fails
+      if: ${{ failure() }}
+      run: |
+        echo "Error: Failed to make script files executable"
+        exit 1
+
     - name: Run the scripts
       run: |
         ./my-script.sh
-        
+      continue-on-error: true
+      # Capture the exit code and display error message if it fails
+      if: ${{ failure() }}
+      run: |
+        echo "Error: Failed to run the scripts"
+        exit 1
+
+    # Add a final step to check for overall workflow status
+    - name: Check Workflow Status
+      run: |
+        if [ ${{ job.status }} == "failure" ]; then
+          echo "Workflow failed with errors."
+          exit 1
+        else
+          echo "Workflow completed successfully."
+        fi
