Update transferusingscp.yml

diff --git a/.github/workflows/transferusingscp.yml b/.github/workflows/transferusingscp.yml
--- a/.github/workflows/transferusingscp.yml
+++ b/.github/workflows/transferusingscp.yml
@@ -6,6 +6,13 @@ on:
       folder_name:
         description: 'Folder to Zip and Deploy'
         required: true
+      environment_type:
+        description: 'Environment Type'
+        required: true
+        options:
+          - Dev
+          - Test
+          - Deploy
 
 jobs:
   build:
@@ -20,16 +27,38 @@ jobs:
         cp -r PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }} ../build
         tar -cvf ${{ github.event.inputs.folder_name }}.tar -C ../build .
         
+    - name: Set Environment Variables based on Environment Type
+      run: |
+        if [[ "${{ github.event.inputs.environment_type }}" == "Dev" ]]; then
+          export HOST="${{ secrets.HOST }}"
+          export USERNAME="${{ secrets.USERNAME }}"
+          export PASSWORD="${{ secrets.PASSWORD }}"
+          export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
+        elif [[ "${{ github.event.inputs.environment_type }}" == "Test" ]]; then
+          export HOST="${{ secrets.HOST_TEST }}"
+          export USERNAME="${{ secrets.USERNAME_TEST }}"
+          export PASSWORD="${{ secrets.PASSWORD_TEST }}"
+          export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY_TEST }}"
+        elif [[ "${{ github.event.inputs.environment_type }}" == "Deploy" ]]; then
+          export HOST="${{ secrets.HOST_DEPLOY }}"
+          export USERNAME="${{ secrets.USERNAME_DEPLOY }}"
+          export PASSWORD="${{ secrets.PASSWORD_DEPLOY }}"
+          export SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}"
+        else
+          echo "Invalid environment type selected."
+          exit 1
+        fi
+
     - name: Copy file via SSH password
       uses: appleboy/scp-action@master
       with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        password: ${{ secrets.PASSWORD }}
-        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        host: ${{ env.HOST }}
+        username: ${{ env.USERNAME }}
+        password: ${{ env.PASSWORD }}
+        key: ${{ env.SSH_PRIVATE_KEY }}
         port: ${{ secrets.PORT }}
         source: "${{ github.event.inputs.folder_name }}.tar"
-        target: "/home/u813984108/domains/sociocast.co/public_html/scimail"
+        target: "/home/u813984108/domains/sociocast.co/public_html/scimail/"
 
     - name: Check out the repository to the runner
       uses: actions/checkout@v4  
