Update transferusingscp.yml

diff --git a/.github/workflows/transferusingscp.yml b/.github/workflows/transferusingscp.yml
--- a/.github/workflows/transferusingscp.yml
+++ b/.github/workflows/transferusingscp.yml
@@ -25,17 +25,18 @@ jobs:
       run: |
           # Add commands to create a ZIP archive of your project in the root directory 
           cd PLM_SOURCE/BUILD_MASTER
-          zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }}
+          zip -r ${{ github.event.inputs.folder_name }}.zip ${{ github.event.inputs.folder_name }} || echo "Error creating ZIP archive."
 
     - name: Create and upload artifact
       uses: actions/upload-artifact@v2
       with:
          name: ${{ github.event.inputs.folder_name }}.zip
-         path: PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip
+         path: PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip || echo "Error uploading artifact."
 
     - name: Move the downloaded .zip file to D:/office/DBA
       run: |
-        mv $GITHUB_WORKSPACE/actions-runner/_work/array/array/PLM_SOURCE/BUILD_MASTER/${{ github.event.inputs.folder_name }}.zip D:/office/DBA/
+        mv $GITHUB_WORKSPACE/${{ github.event.inputs.folder_name }}.zip D:/office/DBA/ || echo "Error moving file to D:/office/DBA."
+
 
 
     #- name: List downloaded files
